### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Daniel-Velasco-Lopez#1]
[Conceptos y funciones de una librería.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Daniel-Velasco-Lopez/files/14566261/Conceptos.y.funciones.de.una.libreria.pdf)

Daniel Velasco López

**Comment by Daisy-GonzalezLita12** [comment]
20% de 20% bien hecho.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
